import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import VisPheno from '../components/visPheno'
// import PCA from '../components/pca'
import PopperComponent from '../components/gitpicker'
import Header from '../components/header'
import ApplyGwasFilters from '../components/applyfilters'
import GWAS from '../components/performgwas'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GWAS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      <Header/>
      <VisPheno/>
      {/* <PCA/> */}
      <ApplyGwasFilters/>
      <GWAS/>
    </div>
  )
}
